apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
  name: multicloud-gitops-extension
  namespace: patterns-operator
spec:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: false
  gitSpec:
    inClusterGitServer: false
    targetRepo: https://github.com/ngner/quarter.git
    targetRevision: feat/thin-upstream-wrapper
  extraValueFiles:
    - values-global.yaml
    - values-hub.yaml
